# Opt-out flag for bundling Kotlin standard library
kotlin.stdlib.default.dependency=false

# Enable Gradle Configuration Cache
org.gradle.configuration-cache=true

# Enable Gradle Build Cache
org.gradle.caching=true

# Workaround for Java version compatibility
org.gradle.internal.JavaVersion.forceJavaVersion=21
